name: check-logs

on:
  schedule:
    - cron:  '*/15 0-2,20-23 * * *'
  push:
    paths:
      - ".github/workflows/check-logs.yml"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch logs client
      run: |
        curl -L https://github.com/origin-finkle/logs/releases/download/v1.1.0/logs-v1.1.0-linux-amd64.tar.gz | tar xzf -
    - name: Fetch latest logs
      run: |
        mkdir -p /tmp/logs
        ./logs extract --folder /tmp/logs --check-on-remote
        [ "$(ls -A /tmp/logs)" ] && exit 1 # stop workflow execution
      env:
        WCL_CLIENT_ID: ${{ secrets.WCL_CLIENT_ID }}
        WCL_CLIENT_SECRET: ${{ secrets.WCL_CLIENT_SECRET }}
    - uses: actions/checkout@v2
      name: Checkout
    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2.4.13
      with:
        hugo-version: '0.85.0'
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Set up environment
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv venv
        source venv/bin/activate
        pip install -r requirements.txt
    - name: Move extractions
      run: |
        cp /tmp/logs/*.json raid-data/
    - name: Analysis
      run: |
        ./logs analyze --analysis-folder ./data/raids --reports-folder ./raid-data --config-folder ./data/config $(ls -A /tmp/logs | cut -d'.' -f1 | xargs)
        python scripts/characters.py
        bash scripts/characters.sh
        for report in $(ls -A /tmp/logs | cut -d'.' -f1); do [[ -f ./data/raids/$report/logs.json ]] && python scripts/generate_hugo_files.py $report; done;
        
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add . --all
        git commit -m "feat: added new raids"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        directory: .
        repository: origin-finkle/wcl-origin
    
    - uses: actions/checkout@v2
      name: "Checkout generated repository"
      with:
        repository: origin-finkle/wcl
        token: ${{ secrets.PAT }}
        path: wcl
    
    - name: Generate website
      run: |
        hugo --destination wcl
        
    - name: Commit generated files
      run: |
        cd wcl
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add . --all
        git commit -m "feat: added new raids"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        directory: wcl
        repository: origin-finkle/wcl
