name: push-master

on:
  push:
    branches:
    - master
    paths:
      - ".github/workflows/push-master.yml"
      - "content/*"
      - "data/*"
      - "layouts/*"
      - "resources/*"
      - "themes/*"
      - "assets/*"
      - "static/*"

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
      with:
        submodules: recursive
    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2.4.13
      with:
        hugo-version: '0.85.0'
    - uses: actions/checkout@v2
      name: "Checkout generated repository"
      with:
        repository: origin-finkle/wcl
        token: ${{ secrets.PAT }}
        path: wcl
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Generate raid files
      run: |
        python -m pip install --upgrade pip
        pip install virtualenv
        virtualenv venv
        source venv/bin/activate
        pip install -r requirements.txt
        ls -l content/raids/
        for report in $(ls -A data/raids); do python scripts/generate_hugo_files.py $report; done;
    
    - name: Generate website
      run: |
        hugo --destination wcl
        
    - name: Commit generated files
      run: |
        cd wcl
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add . --all
        git commit -m "feat: added new raids"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        directory: wcl
        repository: origin-finkle/wcl
