name: push-master

on:
  push:
    branches:
    - master

jobs:
  run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2.4.13
      with:
        hugo-version: '0.85.0'
    - uses: actions/checkout@v2
      name: "Checkout generated repository"
      with:
        repository: origin-finkle/wcl
        token: ${{ secrets.PAT }}
        path: wcl
    
    - name: Generate website
      run: |
        hugo --destination wcl
        
    - name: Commit generated files
      run: |
        cd wcl
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add . --all
        git commit -m "feat: added new raids"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        directory: wcl
        repository: origin-finkle/wcl
